### ISSUE TITLE
Flatpak version 11.2.0 can't find flac but can find opus

### ISSUE THREAD

**Issue by Eonfge** [flacon/flacon#207]
With Flatpak, there is a base-runtime that contains many core libraries. Some of these include 'lame' and 'flac' which means that no application needs to bundle their own version.

For Flacon that means that:
- `flac` is in `/usr/bin/`
- `opusenc` is in `/app/bin/`

Now with the latest version, Flacon can find `openenc` but not `flac`.

This is likely a small bug but it does prevent me from releasing 11.2.0

https://github.com/flathub/com.github.Flacon/pull/50

**Comment by SokoloffA** [comment]
I made the pull request https://github.com/flathub/com.github.Flacon/pull/52

I analyzed the package. Some of the programs, more precisely **flac,  lame,  wavpack and  wvunpack** inside FlatPak are installed not in /app/bin/ but in /usr/bin.

We can fix it by adding the following section to the manifest file:
```
  - name: flacon-progs
    buildsystem: simple
    build-commands:
      - ln -s /usr/bin/flac /app/bin/flac
      - ln -s /usr/bin/lame /app/bin/lame
      - ln -s /usr/bin/wavpack /app/bin/wavpack
      - ln -s /usr/bin/wvunpack /app/bin/wvunpack
```
@Eonfge 
Maybe my decision is crooked, and you will do better.
